spring:
  application:
    name: medicine-inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: 123456

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka