spring:
  application:
    name: user-auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          wso2:
            client-id: ${WSO2_CLIENT_ID}
            client-secret: ${WSO2_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/wso2"
            authorization-grant-type: authorization_code
            scope: openid, email
        provider:
          wso2:
            authorization-uri: https://localhost:9443/oauth2/authorize
            token-uri: https://localhost:9443/oauth2/token
            user-info-uri: https://localhost:9443/oauth2/userinfo
            jwk-set-uri: https://localhost:9443/oauth2/jwks
            user-name-attribute: sub

server:
  port: 8080

app:
  wso2:
    signup-url: ${WSO2_SIGNUP_URL}
  frontend:
    url: ${FRONTEND_URL}
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
